/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PhotoId = IDL.Nat;
export const PhotoMeta = IDL.Record({
  'id' : PhotoId,
  'url' : IDL.Text,
  'caption' : IDL.Text,
  'dateTaken' : IDL.Text,
});

export const idlService = IDL.Service({
  'checkPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getAnniversaryTimestamp' : IDL.Func([], [IDL.Int], ['query']),
  'getDailyMessage' : IDL.Func([], [IDL.Text], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(PhotoMeta)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PhotoId = IDL.Nat;
  const PhotoMeta = IDL.Record({
    'id' : PhotoId,
    'url' : IDL.Text,
    'caption' : IDL.Text,
    'dateTaken' : IDL.Text,
  });
  
  return IDL.Service({
    'checkPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getAnniversaryTimestamp' : IDL.Func([], [IDL.Int], ['query']),
    'getDailyMessage' : IDL.Func([], [IDL.Text], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(PhotoMeta)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };